serenity.project.name=Automatización Front: Patrón Screenplay

webdriver.driver=chrome
webdriver.base.url=http://localhost:5173
headless.mode=false
default.wait.for.timeout=20000

# Encoding y reports
serenity.encoding=UTF-8
serenity.reports.encoding=UTF-8
serenity.compressed.reports=true

# Screenshots
serenity.take.screenshots=FOR_EACH_ACTION

# Carpeta de salida de los resultados
serenity.outputDirectory=target/site/serenity